import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from '@/components/QueryProvider';
import { LoaderProvider } from "@/components/LoaderProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Relationship Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <LoaderProvider>
            <div className="flex flex-col h-screen">
              <Header />
              <main className="flex-1 p-4">{children}</main>
            </div>
          </LoaderProvider>
        </QueryProvider>
      </body>
    </html>
  );
}